[2025-03-23T13:31:48.770+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: healthcare_claims_pipeline.check_data_quality manual__2025-03-23T13:31:31.558460+00:00 [queued]>
[2025-03-23T13:31:48.781+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: healthcare_claims_pipeline.check_data_quality manual__2025-03-23T13:31:31.558460+00:00 [queued]>
[2025-03-23T13:31:48.781+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-23T13:31:48.797+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): check_data_quality> on 2025-03-23 13:31:31.558460+00:00
[2025-03-23T13:31:48.804+0000] {standard_task_runner.py:57} INFO - Started process 596 to run task
[2025-03-23T13:31:48.807+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'healthcare_claims_pipeline', 'check_data_quality', 'manual__2025-03-23T13:31:31.558460+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/healthcare_claims_dag.py', '--cfg-path', '/tmp/tmpso6ew3a7']
[2025-03-23T13:31:48.809+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask check_data_quality
[2025-03-23T13:31:48.857+0000] {task_command.py:415} INFO - Running <TaskInstance: healthcare_claims_pipeline.check_data_quality manual__2025-03-23T13:31:31.558460+00:00 [running]> on host f14adedb7c2a
[2025-03-23T13:31:48.950+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='healthcare_claims_pipeline' AIRFLOW_CTX_TASK_ID='check_data_quality' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T13:31:31.558460+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T13:31:31.558460+00:00'
[2025-03-23T13:31:48.961+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-03-23T13:31:48.968+0000] {logging_mixin.py:151} INFO - Data quality check PASSED: Source and target tables have 2 records
[2025-03-23T13:31:48.968+0000] {python.py:194} INFO - Done. Returned value was: True
[2025-03-23T13:31:48.992+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=healthcare_claims_pipeline, task_id=check_data_quality, execution_date=20250323T133131, start_date=20250323T133148, end_date=20250323T133148
[2025-03-23T13:31:49.019+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-23T13:31:49.046+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
